import type { Metadata } from "next"
import { Cormorant_SC, Inter } from "next/font/google"
import "./globals.css"
import MainProvider from "@/components/providers/MainProvider"

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ["300", "500", "700"],
})

const cormorantSC = Cormorant_SC({
    variable: "--font-cormorant-sc",
    subsets: ["latin"],
    weight: ["300", "500"],
})

export const metadata: Metadata = {
    title: "Framework Team",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={`${cormorantSC.variable} ${inter.variable}`}>
                <MainProvider>{children}</MainProvider>
            </body>
        </html>
    )
}
